### ISSUE TITLE
Use github pages for deployment

### ISSUE THREAD

**Issue by frncsdrk** [frncsdrk/vue-slide-bar-demo-page#2]
@biigpongsatorn We could use github pages instead of netlify or some other hoster. What do you think?

**Comment by biigpongsatorn** [comment]
I'm not seriously.

**Comment by biigpongsatorn** [comment]
I think we could use Github pages. What do you think?

**Comment by frncsdrk** [comment]
We do now:  
[https://frncsdrk.github.io/vue-slide-bar-demo-page/](https://frncsdrk.github.io/vue-slide-bar-demo-page/)

**Comment by biigpongsatorn** [comment]
Very cool.
