### ISSUE TITLE
update version to 1.1.0

### ISSUE THREAD

**Issue by biigpongsatorn** [frncsdrk/vue-slide-bar-demo-page#3]
I published version 1.1.0.
can you update demo page to new version.

update detail.

[Fix value prop type (can be Number or String)](https://github.com/biigpongsatorn/vue-slide-bar/commit/7256839036ba232b4a0410a8b01221f91e9e3057)

[Cursor pointer when hover label](https://github.com/biigpongsatorn/vue-slide-bar/commit/14da0727aa114327fbcb7b2299f7f64c6fbc9446)

**Comment by frncsdrk** [comment]
Will do.

**Comment by biigpongsatorn** [comment]
@frncsdrk  Thank you very much. 😁

**Comment by biigpongsatorn** [comment]
Feature show code is so cool !!!!

**Comment by frncsdrk** [comment]
Thank you! Glad that you like it. Thought it would be nice to have some example code in the same place as the demo.
